use core_macros::fields_blob;

/// Pneumatic (NZB via folder drop) download client settings.
#[fields_blob(
    implementation = "Pneumatic",
    config_contract = "PneumaticSettings",
    protocol = "usenet"
)]
pub struct PneumaticConfig {
    /// Directory to drop NZB files into for processing.
    #[wire(name = "nzbFolder")]
    pub nzb_folder: Option<String>,
    /// Directory for STRM files generated by Pneumatic.
    #[wire(name = "strmFolder")]
    pub strm_folder: Option<String>,
}
