name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  check:
    name: Lint & Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: configuratarr
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          # Only push built binaries on main or dev branches, skip for Dependabot
          skipPush: ${{ github.actor == 'dependabot[bot]' }}

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Nix Flake schema & outputs
        run: nix flake check

      - name: Verify Nix Formatting
        run: |
          nix fmt
          git diff --exit-code

      - name: Verify Options Documentation is Up to Date
        run: |
          nix run .#generate-docs
          git diff --exit-code docs/

      - name: Verify Cargo Formatting
        run: nix develop --command cargo fmt --check

      - name: Verify Rust Lints (Clippy)
        run: nix develop --command cargo clippy --all-targets -- -D warnings

      - name: Run Tests
        run: nix develop --command cargo test
